server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sports_center
    username: root
    password: root
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/data.sql
